export interface KnowledgeEntry {
  id: string;
  title: string;
  category: string;
  tags: string[];
  date?: { year: number; month: number; day?: number };
  summary: string;
  details: string;
  verifiedData?: Record<string, unknown>;
  lessons?: string[];
}

export const marketEvents: KnowledgeEntry[] = [
  {
    id: "covid-crash-2020",
    title: "COVID-19 Crash (March 2020)",
    category: "crash",
    tags: ["covid", "coronavirus", "pandemic", "crash", "2020", "black swan", "march 2020", "liquidity crisis"],
    date: { year: 2020, month: 3 },
    summary: "Fastest crash in history - S&P 500 down 34% in 33 days, BTC dropped 62% in a single day on March 12.",
    details: "The COVID-19 pandemic triggered the fastest bear market in history. The S&P 500 fell 34% from its February 19 high to its March 23 low — just 33 calendar days. Volatility index (VIX) spiked to an all-time high of 82.69, surpassing even 2008 levels. Circuit breakers were triggered 4 times in 2 weeks. Bitcoin experienced 'Black Thursday' on March 12, dropping from ~$7,900 to $3,800 in a single day — a 52% single-day crash — driven by a liquidity crisis where all assets were sold for USD. The Federal Reserve cut rates to 0% and launched unlimited QE. The S&P 500 fully recovered by August 2020 and went on to new all-time highs.",
    verifiedData: { sp500Peak: 3386, sp500Trough: 2237, sp500DropPercent: 34, btcPreCrash: 7900, btcCrashLow: 3800, btcDropPercent: 52, vixPeak: 82.69, recoveryMonths: 5 },
    lessons: ["The fastest crashes often have the fastest recoveries.", "Panic selling at the bottom is the single worst mistake a trader can make.", "Circuit breakers don't stop crashes — they just pause them.", "In a liquidity crisis, all correlations go to 1. Everything sells off together.", "Cash during a crash is a position. It gives you the ability to buy when others are forced to sell."],
  },
  {
    id: "2008-financial-crisis",
    title: "2008 Global Financial Crisis",
    category: "crash",
    tags: ["2008", "financial crisis", "lehman", "subprime", "mortgage", "GFC", "great recession", "bear market"],
    date: { year: 2008, month: 9 },
    summary: "The worst financial crisis since the Great Depression. S&P 500 dropped 58% from Oct 2007 to Mar 2009.",
    details: "Triggered by the collapse of the US subprime mortgage market and the failure of Lehman Brothers on September 15, 2008. S&P 500 fell from 1,576 (Oct 2007 peak) to 666 (March 2009 trough) — a 58% decline over 17 months. Bear Stearns was acquired by JPMorgan in March 2008. AIG was bailed out. The government launched TARP ($700B). The Fed cut rates to 0% and started QE1. Housing prices fell 30% nationally. Unemployment doubled to 10%. The crisis spread globally, causing the European debt crisis. The S&P 500 took until 2013 to recover to 2007 highs — a 6-year recovery.",
    verifiedData: { sp500Peak: 1576, sp500Trough: 666, sp500DropPercent: 58, durationMonths: 17, recoveryYears: 6, unemploymentPeak: 10 },
    lessons: ["When everything correlates to 1, risk management fails. Cash is a position.", "'This time is different' is the most dangerous phrase in markets.", "Leverage amplifies returns in both directions — LTCM and Lehman both had 30:1+ leverage.", "The banking crisis takes years to resolve, not months.", "Bear market rallies can be vicious — 40%+ bounces before lower lows are normal."],
  },
  {
    id: "dot-com-bubble-2000",
    title: "Dot-Com Bubble Burst (2000-2002)",
    category: "crash",
    tags: ["2000", "dot-com", "tech bubble", "NASDAQ", "crash", "internet", "bear market"],
    date: { year: 2000, month: 3 },
    summary: "NASDAQ fell 78% from 5,048 to 1,114 over 2.5 years as the internet bubble deflated.",
    details: "The NASDAQ Composite peaked at 5,048 on March 10, 2000, driven by irrational exuberance for internet companies. Many companies had no earnings, no revenue, and in some cases no business model — but their stocks had exploded. Pets.com, Webvan, and thousands of others went bankrupt. The NASDAQ bottomed at 1,114 on October 9, 2002 — a 78% decline over 2.5 years. The S&P 500 fell 49% from peak to trough. The Fed had been raising rates from 4.75% to 6.5% through 1999-2000. RSI showed bearish divergence for MONTHS before the top. Declining volume on rallies was a clear warning sign. Insider selling peaked just before the crash.",
    verifiedData: { nasdaqPeak: 5048, nasdaqTrough: 1114, nasdaqDropPercent: 78, sp500DropPercent: 49, durationMonths: 31, rateHikeRange: "4.75%-6.5%" },
    lessons: ["When taxi drivers give stock tips, it's time to sell.", "RSI divergence over multiple timeframes is one of the most reliable topping signals.", "Insider selling is the most leading indicator there is.", "Bubbles last longer than anyone expects. Fighting the trend is financial suicide.", "First bounce after a crash is usually a trap — dead cat bounce."],
  },
  {
    id: "2010-flash-crash",
    title: "2010 Flash Crash (May 6, 2010)",
    category: "crash",
    tags: ["2010", "flash crash", "algorithmic", "high frequency trading", "HFT", "Dow", "liquidity"],
    date: { year: 2010, month: 5, day: 6 },
    summary: "The Dow dropped 998 points (9%) in minutes, then fully recovered in 30 minutes.",
    details: "On May 6, 2010, the Dow Jones Industrial Average suddenly dropped about 998 points (approximately 9%) in about 36 minutes, only to recover most of the loss within the next 30 minutes. It was the second-largest point swing in Dow history up to that point. The crash was triggered by a large sell order ($4.1B in E-Mini S&P futures) executed by an algorithm that didn't account for price impact. High-frequency trading algorithms amplified the move. Many stocks traded for pennies or thousands of dollars during the chaos. Circuit breakers were introduced/modified as a result. This event highlighted the dangers of algorithmic trading without proper safeguards.",
    verifiedData: { dowDrop: 998, dowDropPercent: 9, durationMinutes: 36, recoveryMinutes: 30, sellOrderSize: "4.1B" },
    lessons: ["Stop losses don't work in flash crashes — you'll get filled at the worst possible price.", "Algorithmic trading creates liquidity in normal markets but can destroy it in panics.", "Limit orders, not market orders, protect you during extreme volatility.", "The market can stay irrational longer than you can stay solvent."],
  },
  {
    id: "2013-taper-tantrum",
    title: "2013 Taper Tantrum",
    category: "economic_event",
    tags: ["2013", "taper tantrum", "fed", "QE", "bond market", "interest rates", "Bernanke"],
    date: { year: 2013, month: 5 },
    summary: "Bond yields spiked sharply after Fed Chairman Bernanke suggested tapering QE, causing a global sell-off.",
    details: "On May 22, 2013, Fed Chairman Ben Bernanke suggested the Fed might begin tapering its quantitative easing program. The 10-year Treasury yield spiked from 1.6% to 3.0% in a matter of weeks. Emerging markets sold off sharply as capital flowed back to the US. The S&P 500 initially dropped about 6% but recovered quickly. The 'taper tantrum' became a textbook example of how sensitive markets are to central bank communication.",
    verifiedData: { yieldPreSpike: 1.6, yieldPostSpike: 3.0, sp500Drop: 6 },
    lessons: ["Never fight the Fed.", "Central bank communication is a powerful market tool.", "Emerging markets are the first to suffer when US rates rise.", "The bond market is smarter than the stock market — watch yields closely."],
  },
  {
    id: "2015-china-crash",
    title: "2015 Chinese Stock Market Crash",
    category: "crash",
    tags: ["2015", "china", "shanghai", "crash", "emerging markets", "yuan"],
    date: { year: 2015, month: 6 },
    summary: "Shanghai Composite crashed 40% in 3 months as China's margin-fueled bubble burst.",
    details: "The Shanghai Composite Index peaked at 5,166 on June 12, 2015, driven by massive margin trading. When the government tried to cool the market, it triggered a cascade of margin calls. The index fell to about 2,850 by August — a 45% decline. The government attempted unprecedented interventions including banning major shareholders from selling, using state funds to buy stocks, and even arresting short-sellers. None of these worked. Bitcoin dropped from $300 to $200 during this period, showing 33% correlation. The Chinese yuan was devalued in August 2015, sending shockwaves through global markets.",
    verifiedData: { shanghaiPeak: 5166, shanghaiTrough: 2850, shanghaiDropPercent: 45, btcImpact: "300 to 200" },
    lessons: ["When a government tries to stop a crash, it usually makes it worse.", "Margin-fueled rallies end in margin-fueled crashes.", "Government intervention in free markets creates more distortion than stability.", "China's markets are not as decoupled from global markets as people think."],
  },
  {
    id: "2018-crypto-winter",
    title: "2018 Crypto Winter",
    category: "crash",
    tags: ["2018", "crypto winter", "bitcoin", "BTC", "bear market", "cryptocurrency"],
    date: { year: 2018, month: 1 },
    summary: "BTC fell 84% from $19,783 to $3,122 over 12 months in the deepest crypto bear market.",
    details: "Bitcoin peaked at $19,783 on December 17, 2017, after a parabolic 1,878% rally in 12 months. RSI was above 90 on weekly charts — extreme overbought. The Coinbase app became the #1 download in the App Store. Media frenzy was at peak mania. The decline lasted all of 2018, with Bitcoin bottoming at $3,122 on December 15, 2018 — an 84% decline. The 'blockchain not bitcoin' narrative became popular as the price crashed. ICOs that raised billions in 2017 mostly went to zero. This was the first real crypto bear market cycle and taught the industry about the depth of crypto drawdowns.",
    verifiedData: { btcPeak: 19783, btcTrough: 3122, btcDropPercent: 84, durationMonths: 12, peakRSIWeekly: "90+" },
    lessons: ["After a parabolic move, the crash is proportional.", "80-90% drawdowns are normal in crypto — position size accordingly.", "Never buy at the peak of media frenzy.", "The 'this time is different' narrative is strongest at the top.", "Bear markets in crypto last 12-18 months. Plan accordingly."],
  },
  {
    id: "2022-crypto-winter",
    title: "2022 Crypto Winter (LUNA/FTX/3AC)",
    category: "crash",
    tags: ["2022", "crypto winter", "luna", "ftx", "3AC", "contagion", "crash", "bankruptcy"],
    date: { year: 2022, month: 5 },
    summary: "A cascade of failures: LUNA (-99.9%), 3AC liquidation, Celsius bankruptcy, FTX collapse ($8B hole).",
    details: "The 2022 crypto winter was defined by a contagion cascade that destroyed multiple major entities. Terra LUNA's algorithmic stablecoin (UST) de-pegged in May 2022, causing LUNA to go from $119 to effectively zero — a 99.9% loss in one week. This triggered the collapse of Three Arrows Capital (3AC), a major crypto hedge fund that was overleveraged on LUNA. 3AC's liquidation then caused Celsius Network (a crypto lending platform) to freeze withdrawals and file for bankruptcy. The final domino was FTX, which collapsed in November 2022 after a CoinDesk report revealed Alameda Research was largely funded by FTX's native token FTT. FTX filed for bankruptcy with an estimated $8B hole. Sam Bankman-Fried was later convicted of fraud. Bitcoin bottomed at $15,500 in November 2022, down 78% from its November 2021 high of $69,000.",
    verifiedData: { btcPeak: 69000, btcTrough: 15500, btcDropPercent: 78, lunaPeak: 119, lunaDropPercent: 99.9, ftxHole: "8B", durationMonths: 12 },
    lessons: ["Contagion in crypto travels fast — LUNA to 3AC to Celsius to FTX, each domino causing the next.", "If a yield seems too good to be true, it's almost certainly a Ponzi scheme.", "Not your keys, not your coins — exchange risk is real.", "Correlation during crypto crashes approaches 1 — diversification within crypto doesn't protect you.", "The strongest assets drop the least during contagion events — relative strength matters."],
  },
  {
    id: "2023-banking-crisis",
    title: "2023 Banking Crisis (SVB/Credit Suisse)",
    category: "crash",
    tags: ["2023", "SVB", "silicon valley bank", "credit suisse", "banking crisis", "regional banks", "UB"],
    date: { year: 2023, month: 3 },
    summary: "SVB collapsed in 48 hours ($42B withdrawn in one day via Twitter-fueled bank run). Credit Suisse forced into UBS merger.",
    details: "Silicon Valley Bank (SVB) collapsed on March 10, 2023, in the fastest bank run in history. $42 billion was withdrawn in a single day, driven by venture capital firms coordinating on Twitter and WhatsApp. SVB had made the classic mistake of borrowing short-term deposits and investing long-term in US Treasuries — when rates rose, they were forced to sell at massive losses. Signature Bank and First Republic Bank also failed. Credit Suisse, a global systemically important bank, was forced into an emergency merger with UBS for $3.2B (a fraction of its book value). Unlike 2008, regulators responded very quickly. Interestingly, BTC rallied from $20,000 to $30,000 during this period, establishing crypto as a potential hedge against banking stress.",
    verifiedData: { svbWithdrawalDay: "42B", creditSuisseAcquisition: "3.2B", btcRally: "20K to 30K", timelineDays: 10 },
    lessons: ["Social media has made bank runs instantaneous — SVB failed faster than any bank in history.", "Duration mismatch (borrowing short, lending long) is still the #1 risk for banks.", "Crypto can act as a hedge during banking crises.", "Regulatory response in 2023 was much faster than 2008 — lessons were learned.", "When a 'too big to fail' bank fails, the government WILL step in."],
  },
  {
    id: "2017-crypto-bull-run",
    title: "2017 Crypto Bull Run",
    category: "bull_run",
    tags: ["2017", "bull run", "bitcoin", "BTC", "crypto", "parabolic", "mania"],
    date: { year: 2017, month: 1 },
    summary: "BTC rallied 1,878% in 12 months from $1,000 to $19,783 — the first mainstream crypto bubble.",
    details: "Bitcoin started 2017 at around $1,000. By December 17, 2017, it peaked at $19,783 — a 1,878% rally in 12 months. The rally was driven by retail euphoria, ICO mania, and the launch of Bitcoin futures on CME. RSI stayed above 80 for weeks at a time. The Coinbase app became the #1 download in the Apple App Store. 'Blockchain not Bitcoin' became a common refrain. The narrative shifted from 'digital cash' to 'digital gold' to 'institutional adoption is coming.' The peak coincided with the launch of CME Bitcoin futures — the classic 'sell the news' event. Every altcoin followed Bitcoin higher, with many producing 100x+ returns during the year.",
    verifiedData: { btcStart: 1000, btcPeak: 19783, rallyPercent: 1878, durationMonths: 12 },
    lessons: ["Parabolic moves end in catastrophic crashes. Take profits on the way up.", "When your Uber driver asks about Bitcoin, it's time to sell.", "RSI above 80 for weeks is not sustainable — respect extreme readings.", "'Sell the news' is a real phenomenon — when 'everyone' expects something, it's already priced in.", "Altcoins that 100x in a year will 90%+ drawdown in the bear market."],
  },
  {
    id: "2023-2024-ai-rally",
    title: "2023-2024 AI Rally",
    category: "bull_run",
    tags: ["2023", "2024", "AI", "NVIDIA", "magnificent seven", "tech rally", "artificial intelligence"],
    date: { year: 2023, month: 1 },
    summary: "NVIDIA rallied 757% in 15 months, S&P 500 driven by the Magnificent Seven mega-cap tech stocks.",
    details: "The AI rally began with the launch of ChatGPT in November 2022. NVIDIA, as the primary beneficiary of AI infrastructure spending, rallied from around $150 in January 2023 to over $1,200 by mid-2024 — a 757% increase in 18 months. The S&P 500 rally in 2023-2024 was historically concentrated in the 'Magnificent Seven' (Apple, Microsoft, Google, Amazon, NVIDIA, Meta, Tesla), with these stocks accounting for the vast majority of index gains. This concentration risk became a major concern. The narrative shifted from 'AI is coming' to 'AI is here and it's transformative.' Unlike the dot-com era, many of these companies had actual earnings. However, valuations became stretched by historical standards.",
    verifiedData: { nvidiaStart: 150, nvidiaPeak: 1200, nvidiaRallyPercent: 757, sectorsLeading: "Magnificent Seven" },
    lessons: ["Concentration risk is the hidden danger of index investing — 7 stocks driving the entire market is not healthy.", "When a sector becomes 'obvious,' it's usually closer to the top than the bottom.", "The difference between 2000 and 2024: these companies have real earnings.", "NVIDIA at 50x+ earnings is priced for perfection — any miss will be punished severely.", "Not every tech rally is a bubble, but every tech rally has bubble-like characteristics."],
  },
  {
    id: "2009-2020-bull-market",
    title: "2009-2020 Longest Bull Market",
    category: "bull_run",
    tags: ["2009", "2020", "bull market", "S&P 500", "longest", "QE", "ZIRP"],
    date: { year: 2009, month: 3 },
    summary: "S&P 500 up 408% over 11 years — the longest bull market in history, fueled by zero interest rates and QE.",
    details: "From the March 2009 low of 666 to the February 2020 peak of 3,386, the S&P 500 rose 408% over 11 years — the longest bull market in history. This was driven by unprecedented monetary policy: zero interest rates (ZIRP) from 2009-2015, multiple rounds of quantitative easing (QE1, QE2, QE3), and eventually near-zero rates again in 2019. The bull market had multiple 'scares' (2011 debt ceiling, 2015 China crash, 2018 Q4 sell-off) but each dip was bought. The 'wall of worry' was constant — most of the rally happened when sentiment was negative. Low VIX became the norm. 'There is no alternative' (TINA) was the dominant narrative for stocks vs bonds.",
    verifiedData: { sp500Start: 666, sp500Peak: 3386, rallyPercent: 408, durationYears: 11, fedRateRange: "0%-2.5%" },
    lessons: ["Bull markets climb a wall of worry — being too bearish can be as costly as being too bullish.", "Don't fight the Fed — central bank liquidity is the most powerful force in markets.", "'TINA' (There Is No Alternative) is a powerful narrative that keeps money in stocks.", "Every bull market ends eventually, but timing it is a fool's errand.", "The biggest risk is being out of the market during the best days."],
  },
  {
    id: "black-monday-1987",
    title: "Black Monday (October 19, 1987)",
    category: "crash",
    tags: ["1987", "black monday", "crash", "Dow", "program trading", "portfolio insurance"],
    date: { year: 1987, month: 10, day: 19 },
    summary: "The Dow fell 22.6% in a single day — the largest single-day percentage decline in history.",
    details: "On October 19, 1987, the Dow Jones Industrial Average fell 508 points, or 22.6%, in a single day — the largest single-day percentage decline in US stock market history. The crash was triggered by a combination of computerized program trading, portfolio insurance strategies that amplified selling, and international tensions. Unlike 1929, the market did not lead to a depression — the Fed provided liquidity and the market recovered within 2 years. Circuit breakers (trading halts) were introduced as a direct result of Black Monday. The crash taught markets about the dangers of algorithmic trading and the importance of providing liquidity during panics.",
    verifiedData: { dowDrop: 508, dowDropPercent: 22.6, recoveryYears: 2 },
    lessons: ["Portfolio insurance (often hedging with futures) doesn't work when everyone tries to do it at once.", "The Fed providing liquidity stopped the crash from becoming a depression — lesson for 2008.", "Algorithmic trading can turn a normal sell-off into a crash.", "Complete market recovery from the single worst crash in history took only 2 years."],
  },
  {
    id: "1997-asian-crisis",
    title: "1997 Asian Financial Crisis",
    category: "crash",
    tags: ["1997", "asia", "currency crisis", "thailand", "contagion", "emerging markets"],
    date: { year: 1997, month: 7 },
    summary: "Started with Thailand's baht float on July 19, 1997. Spread across Asia causing currency collapses and IMF bailouts.",
    details: "The Asian Financial Crisis began on July 19, 1997, when Thailand was forced to float the baht after depleting its foreign currency reserves defending the currency peg. The baht collapsed, and contagion spread rapidly to Indonesia, South Korea, Malaysia, and the Philippines. The IMF stepped in with bailout packages totaling over $100B. The S&P 500 dropped about 10% but recovered relatively quickly. The crisis exposed the dangers of fixed exchange rate regimes, short-term foreign borrowing, and crony capitalism. It had a lasting impact on Asian economic policy.",
    verifiedData: { sp500Impact: 10, imfBailoutTotal: "100B+" },
    lessons: ["Currency crises spread faster than anyone expects.", "Fixed exchange rate regimes are vulnerable to speculative attack.", "Short-term foreign currency borrowing is a deadly risk for emerging markets.", "IMF bailouts come with harsh conditions that deepen the initial economic pain."],
  },
  {
    id: "1998-ltcm-collapse",
    title: "1998 LTCM / Russian Crisis",
    category: "crash",
    tags: ["1998", "LTCM", "long term capital management", "russia", "default", "hedge fund", "leverage"],
    date: { year: 1998, month: 8 },
    summary: "Russia defaulted on domestic debt. LTCM ($4.6B lost) collapsed — a hedge fund run by Nobel laureates.",
    details: "In August 1998, Russia defaulted on its domestic debt and devalued the ruble. This triggered a global flight to quality. Long-Term Capital Management (LTCM), a hedge fund run by Nobel Prize-winning economists (including Myron Scholes and Robert Merton), lost $4.6 billion in a few months and was bailed out by a consortium of banks arranged by the Fed. LTCM had over 30:1 leverage and their 'market-neutral' strategies all failed simultaneously because correlations went to 1. The S&P 500 dropped 19% in 6 weeks. The Fed cut rates 3 times to provide liquidity.",
    verifiedData: { ltcmLoss: "4.6B", ltcmLeverage: "30:1", sp500Drop: 19, fedRateCuts: 3 },
    lessons: ["Even Nobel Prize winners blow up with too much leverage.", "When correlations go to 1, every 'hedge' fails simultaneously.", "30:1 leverage means a 3% move against you wipes out 90% of your capital.", "The Fed will step in to prevent systemic collapse, but not to save individual players.", "If a strategy is 'market neutral,' ask: neutral to WHAT? If everything correlates, nothing is neutral."],
  },
  {
    id: "2021-nft-mania",
    title: "2021 NFT Mania / Crypto Bull Run",
    category: "bull_run",
    tags: ["2021", "NFT", "crypto", "bitcoin", "eth", "bull run", "mania", "ape"],
    date: { year: 2021, month: 1 },
    summary: "BTC reached $69,000, ETH hit $4,800, NFT market exploded to $17B in a massive crypto bull run.",
    details: "The 2021 crypto bull run was fueled by unprecedented monetary stimulus (COVID stimulus checks), institutional adoption (MicroStrategy, Tesla buying BTC), and the NFT explosion. Bitcoin rallied from $29,000 in January 2021 to $69,000 in November 2021. Ethereum went from $730 to $4,800. NFT trading volume hit $17B for the year, with projects like CryptoPunks and Bored Ape Yacht Club capturing mainstream attention. The 'supercycle' narrative emerged — the idea that crypto would never have another bear market. This narrative proved false as 2022 brought one of the worst crypto winters.",
    verifiedData: { btcStart: 29000, btcPeak: 69000, ethStart: 730, ethPeak: 4800, nftVolume: "17B" },
    lessons: ["The 'supercycle' narrative is always wrong — every bull market ends.", "Stimulus money flows into risk assets first, and leaves them first.", "NFT mania was a classic speculative mania — JPEGs trading for millions.", "BTC leading and altcoins following is the typical pattern — altcoins fall harder.", "Institutions 'buying the top' (MicroStrategy at $60K+) is a warning sign, not confirmation."],
  },
  {
    id: "2024-btc-halving",
    title: "Bitcoin Halving (April 2024)",
    category: "crypto_event",
    tags: ["2024", "bitcoin", "halving", "BTC", "mining", "supply", "block reward"],
    date: { year: 2024, month: 4 },
    summary: "Bitcoin's 4th halving reduced block reward from 6.25 to 3.125 BTC. Previous halvings preceded major bull runs.",
    details: "Bitcoin's fourth halving occurred at block 840,000 in April 2024, reducing the block reward from 6.25 BTC to 3.125 BTC. The halving occurs approximately every 4 years (210,000 blocks). Previous halvings: 2012 (50→25), 2016 (25→12.5), 2020 (12.5→6.25). Historically, each halving has preceded a major bull run within 12-18 months. However, the diminishing impact of each halving (as a percentage of total supply) means the effect may be less pronounced over time.",
    verifiedData: { blockHeight: 840000, rewardBefore: 6.25, rewardAfter: 3.125, halvingNumber: 4 },
    lessons: ["Bitcoin halvings are well-known events — 'buy the rumor, sell the news' may apply.", "Each halving has less impact as a % of total supply — diminishing marginal effects.", "Miners are forced to become more efficient after each halving.", "The 12-18 month post-halving window has historically been the most bullish period."],
  },
];
