import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, AlertOctagon } from "lucide-react";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "TradePilot disclaimer — our AI copilot provides educational analysis only. Not financial advice. Trading involves risk.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen py-16 px-6 max-w-3xl mx-auto flex flex-col justify-between" style={{ backgroundColor: "var(--color-bg-primary)" }}>
      <div>
        <Link href="/" className="inline-flex items-center gap-1.5 text-xs font-semibold mb-8 text-zinc-500 hover:text-white transition-colors">
          <ArrowLeft size={14} /> Back to Home
        </Link>

        <div className="flex items-center gap-2 mb-6 text-teal-400">
          <AlertOctagon size={24} />
          <h1 className="text-2xl font-bold text-white">Legal & Risk Disclaimer</h1>
        </div>

        <p className="text-xs mb-8 text-zinc-500">Last updated: July 12, 2026</p>

        <div className="space-y-6 text-sm text-zinc-300 leading-relaxed">
          <section className="p-4 rounded-xl border border-red-500/20 bg-red-500/5 text-red-200">
            <h2 className="text-base font-bold text-red-100 mb-2">CRITICAL RISK WARNING</h2>
            <p>
              Trading financial markets (including cryptocurrencies, forex, commodities, and equities) involves substantial risk of loss and is not suitable for every investor. You can lose all of your deposited capital. Do not trade with money you cannot afford to lose.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">1. Not Financial Advice</h2>
            <p>
              All software tools, calculators, metrics, backtesting data, and AI insights generated by TradePilot are provided for **educational and analytical purposes only**. TradePilot does not provide customized financial, investment, legal, tax, or trading advice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">2. No Investment Recommendations</h2>
            <p>
              AI chat responses, automated technical indicators, support and resistance boundaries, bias levels, and setup grades do not constitute a solicitation, recommendation, or endorsement to buy or sell any financial instrument. Do not execute trades based solely on information presented by this Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">3. Historical Performance</h2>
            <p>
              Past performance, including simulated backtesting results, is not indicative or a guarantee of future results. Backtesting does not take into account real-world execution factors such as order execution latency, slippage, liquidity constraints, swap fees, or bid-ask spread variations.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">4. AI Limitations</h2>
            <p>
              Our behavioral evaluation systems and chart analysis engines rely on large language models (LLMs). While we take steps to ensure high prompt accuracy and parameter constraints, AI models can produce hallucinations, incorrect data points, or mathematical discrepancies. Always cross-reference AI-generated telemetry with standard charting tools.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">5. Regulatory Compliance</h2>
            <p>
              TradePilot is not registered as an investment advisor, broker-dealer, or financial analyst with the Securities and Exchange Board of India (SEBI), the US Securities and Exchange Commission (SEC), or any other financial regulatory authority. We do not offer brokerage or direct asset custody services.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">6. Limitation of Liability</h2>
            <p>
              You assume full responsibility for your trading and investment decisions. TradePilot, its developers, founders, and content providers are not liable for any financial losses, capital drawdowns, or emotional distress you experience in connection with your use of our platform.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">7. Consult a Licensed Professional</h2>
            <p>
              If you require specific, personalized advice concerning a financial plan, asset allocation, or trade execution, please consult a registered, licensed, and qualified financial advisor in your jurisdiction.
            </p>
          </section>
        </div>
      </div>

      <footer className="mt-16 pt-8 border-t border-zinc-800 text-[11px] text-zinc-500 text-center">
        © 2026 TradePilot. Educational and analytical services only.
      </footer>
    </div>
  );
}
