import type { Metadata } from "next";
import { buildMetadata } from "@/lib/seo";
import { AlertOctagon } from "lucide-react";
import LegalLayout, { LegalSection, P, Strong } from "@/components/legal/LegalLayout";

export const metadata: Metadata = buildMetadata({
  title: "Risk Disclaimer — Educational Analysis, Not Financial Advice",
  description:
    "TradCopilot provides educational market analysis only. Not financial advice; no trade execution; not a registered advisor or broker-dealer. Trading involves substantial risk of loss.",
  path: "/disclaimer",
});

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Legal & Risk Disclaimer" updated="July 12, 2026" icon={<AlertOctagon size={24} />}>
      <section className="p-4 rounded-xl border border-red-500/20 bg-red-500/5 text-red-200">
        <h2 className="text-base font-bold text-red-100 mb-2">CRITICAL RISK WARNING</h2>
        <p>
          Trading financial markets (including cryptocurrencies, forex, commodities, and equities) involves substantial risk of loss and is not suitable for every investor. You can lose all of your deposited capital. Do not trade with money you cannot afford to lose.
        </p>
      </section>

      <LegalSection title="1. Not Financial Advice">
        <P>
          All software tools, calculators, metrics, backtesting data, and AI insights generated by TradCopilot are provided for <Strong>educational and analytical purposes only</Strong>. TradCopilot does not provide customized financial, investment, legal, tax, or trading advice.
        </P>
      </LegalSection>

      <LegalSection title="2. No Investment Recommendations">
        <P>
          AI chat responses, automated technical indicators, support and resistance boundaries, bias levels, and setup grades do not constitute a solicitation, recommendation, or endorsement to buy or sell any financial instrument. Do not execute trades based solely on information presented by this Service.
        </P>
      </LegalSection>

      <LegalSection title="3. Historical Performance">
        <P>
          Past performance, including simulated backtesting results, is not indicative or a guarantee of future results. Backtesting does not take into account real-world execution factors such as order execution latency, slippage, liquidity constraints, swap fees, or bid-ask spread variations.
        </P>
      </LegalSection>

      <LegalSection title="4. AI Limitations">
        <P>
          Our behavioral evaluation systems and chart analysis engines rely on large language models (LLMs). While we take steps to ensure high prompt accuracy and parameter constraints, AI models can produce hallucinations, incorrect data points, or mathematical discrepancies. Always cross-reference AI-generated telemetry with standard charting tools.
        </P>
      </LegalSection>

      <LegalSection title="5. Regulatory Compliance">
        <P>
          TradCopilot is not registered as an investment advisor, broker-dealer, or financial analyst with the Securities and Exchange Board of India (SEBI), the US Securities and Exchange Commission (SEC), or any other financial regulatory authority. We do not offer brokerage or direct asset custody services.
        </P>
      </LegalSection>

      <LegalSection title="6. Limitation of Liability">
        <P>
          You assume full responsibility for your trading and investment decisions. TradCopilot, its developers, founders, and content providers are not liable for any financial losses, capital drawdowns, or emotional distress you experience in connection with your use of our platform.
        </P>
      </LegalSection>

      <LegalSection title="7. Consult a Licensed Professional">
        <P>
          If you require specific, personalized advice concerning a financial plan, asset allocation, or trade execution, please consult a registered, licensed, and qualified financial advisor in your jurisdiction.
        </P>
      </LegalSection>
    </LegalLayout>
  );
}